# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.3"
manifest_format = "2.0"
project_hash = "5b0b12c94f925becc73e6eea3fb413b27e911d5b"

[[deps.HelloWorld]]
path = ".."
uuid = "7f3d4f46-94b1-4a90-803b-1e6098c77ffb"
version = "1.0.0-DEV"
